### ISSUE TITLE
Windows 10 application crash at startup

### ISSUE THREAD

**Issue by sievertz** [mbos/Pass4Win#73]
Hey,

I just tried to download and install the 1.1.2 but get a crash on startup (older versions also crashed).
I get two errors in the eventlog when trying to launch the application:
1.  Application error
   Faulting application name: Pass4Win.exe, version: 1.1.2.0, time stamp: 0x5618164d
   Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f3b2a
   Exception code: 0xe0434352
   Fault offset: 0x000b3e28
   Faulting process ID: 0xf1c
   Faulting application start time: 0x01d10a979aa1c701
   Faulting application path: C:\Users\Dennis\Desktop\Pass4Win\Pass4Win.exe
   Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
   Report ID: b837f307-ec9b-49c2-9dc2-9ba861ca010c
   Faulting package full name: 
   Faulting package-relative application ID: 
2. .NET Runtime error
   Application: Pass4Win.exe
   Framework Version: v4.0.30319
   Description: The process was terminated due to an unhandled exception.
   Exception Info: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
   Stack:
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pass4Win.frmMain, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon)
   at Pass4Win.frmMain..ctor()
   at Pass4Win.Program.Main()

Could you please look into what might be wrong?
Thank you very much!
Siwan

**Comment by Slackerony** [comment]
Check https://github.com/mbos/Pass4Win/issues/68 see if that doesn't fix it :)

**Comment by mbos** [comment]
check #71 it's the same.

**Comment by sievertz** [comment]
Hmm that is weird, it's basically exactly the same issue, but I do have git
version 2.6.1 installed.

I can start Git without any issues and gpg4win is installed (I also have a
pgp key since before).

Ah well my issue was closed, guess I'll continue to look at #71 :)

Thanks for the help!

mån 19 okt. 2015 kl 20:22 skrev Slackerony notifications@github.com:
