### ISSUE TITLE
Latest release doesn't seem to work

### ISSUE THREAD

**Issue by mkaito** [mbos/Pass4Win#79]
Log Name:      Application
Source:        .NET Runtime
Date:          10/26/2015 2:00:19 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WinHydra
Description:
Application: Pass4Win.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at System.Windows.Forms.ListBox.set_SelectedIndex(Int32)
   at Pass4Win.FrmMain.FillFileList(System.String)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pass4Win.FrmMain, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon)
   at Pass4Win.FrmMain.CreateNodes()
   at Pass4Win.FrmMain..ctor()
   at Pass4Win.Program.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-10-26T02:00:19.000000000Z" />
    <EventRecordID>2783</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WinHydra</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Pass4Win.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at System.Windows.Forms.ListBox.set_SelectedIndex(Int32)
   at Pass4Win.FrmMain.FillFileList(System.String)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pass4Win.FrmMain, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon)
   at Pass4Win.FrmMain.CreateNodes()
   at Pass4Win.FrmMain..ctor()
   at Pass4Win.Program.Main()
</Data>
  </EventData>
</Event>

**Comment by TechnicallyJoe** [comment]
System.ArgumentOutOfRangeException
Stack:
at System.Windows.Forms.ListBox.set_SelectedIndex(Int32)
at Pass4Win.FrmMain.FillFileList(System.String)

**Comment by mbos** [comment]
There's no null check on that function. So if an empty directory is the root it will crash.

**Comment by mkaito** [comment]
Hmmm pretty sure it's not empty, but maybe the config is gone after reinstall?

**Comment by mbos** [comment]
Nah it checks on the config. I made a new exe, you can copy it over the old one. I made a null check on a couple of levels. Could you try it out?
https://s3-eu-west-1.amazonaws.com/pass4win/Pass4Win+exe.zip

**Comment by mkaito** [comment]
Nope :frowning: 

Log Name:      Application
Source:        .NET Runtime
Date:          10/27/2015 1:33:14 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WinHydra
Description:
Application: Pass4Win.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at System.Windows.Forms.ListBox.set_SelectedIndex(Int32)
   at Pass4Win.FrmMain.FillFileList(System.String)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pass4Win.FrmMain, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon)
   at Pass4Win.FrmMain.CreateNodes()
   at Pass4Win.FrmMain..ctor()
   at Pass4Win.Program.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-10-27T01:33:14.000000000Z" />
    <EventRecordID>2870</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WinHydra</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Pass4Win.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at System.Windows.Forms.ListBox.set_SelectedIndex(Int32)
   at Pass4Win.FrmMain.FillFileList(System.String)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pass4Win.FrmMain, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon)
   at Pass4Win.FrmMain.CreateNodes()
   at Pass4Win.FrmMain..ctor()
   at Pass4Win.Program.Main()
</Data>
  </EventData>
</Event>

**Comment by mbos** [comment]
Okay. Well that doesn't really make sense to me. Basically it complains it has no first entry of the list, but it's not an empty list. Weird shit. Anyway I made a catch for it so it shouldn't crash the application anymore:
https://s3-eu-west-1.amazonaws.com/pass4win/Pass4Win+exe.zip

No idea why it happens though. Could you make screenshot/list how your rootdirectory looks like with some info about the alphabatically first file (what's the size, is it a valid gpg file)?
